# Generated by Django 5.2.12 on 2026-03-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_item_list'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE lists_item SET list_id = (SELECT id FROM lists_list LIMIT 1) WHERE list_id IS NULL",
            reverse_sql="UPDATE lists_item SET list_id = NULL"
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
