# Generated by Django 5.2.12 on 2026-03-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
    ]
